In [1]:
import pandas as pd
import numpy as np

In [2]:
def value_counts_with_percentages(series, dropna=False, decimals=2):
    counts = series.value_counts(dropna=dropna)
    percents = (series.value_counts(normalize=True, dropna=dropna) * 100).round(decimals)
    return pd.DataFrame({
        'count': counts,
        'percent': percents
    })

In [3]:
full_labels_df = pd.read_csv('label_15_85.csv')
full_labels_df.head()
full_labels_df.shape

(16205, 11)

In [6]:

df = pd.read_csv("label_15_85.csv")

check = df[['index']].copy()
check['df_index'] = df.index
check = check[['df_index', 'index']]

check.head(20)

    df_index  index
0          0      5
1          1      0
2          2      1
3          3      3
4          4      7
5          5      4
6          6     14
7          7    113
8          8     15
9          9     16
10        10    114
11        11    115
12        12    116
13        13     17
14        14    117
15        15    118
16        16     18
17        17    119
18        18    120
19        19     19

In [8]:
range(len(full_labels_df))

range(0, 16205)

In [9]:
full_labels_new_index_df = full_labels_df.copy()
full_labels_new_index_df['old_index'] = full_labels_new_index_df['index']
full_labels_new_index_df['index'] = range(len(full_labels_new_index_df))
full_labels_new_index_df

,index,datetime,service,instance,message,level,anomaly_type,st_time,ed_time,duration,data_type,old_index
0,0,2021-07-01,webservice,webservice2,"2021-07-01 11:16:52,953 | WARNING | 0.0.0.3 | ...",WARNING,[memory_anomalies],2021-07-01 11:06:52.953000,2021-07-01 11:16:52.953000,600,train,5
1,1,2021-07-01,dbservice,dbservice1,"2021-07-01 11:54:27,616 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-01 11:44:27.616000,2021-07-01 11:54:27.616000,600,train,0
2,2,2021-07-01,dbservice,dbservice1,"2021-07-01 12:25:08,804 | WARNING | 0.0.0.4 | ...",WARNING,[normal memory freed label],2021-07-01 12:25:08.804000,2021-07-01 12:35:08.804000,600,train,1
3,3,2021-07-01,dbservice,dbservice2,"2021-07-01 12:54:56,480 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-01 12:44:56.480000,2021-07-01 12:54:56.480000,600,train,3
4,4,2021-07-01,redisservice,redisservice1,"2021-07-01 13:18:43,143 | WARNING | 0.0.0.1 | ...",WARNING,[memory_anomalies],2021-07-01 13:08:43.143000,2021-07-01 13:18:43.143000,600,train,7
...,...,...,...,...,...,...,...,...,...,...,...,...
16200,16200,2021-07-31,mobservice,mobservice2,"2021-07-31 23:47:41,157 | WARNING | 0.0.0.4 | ...",WARNING,[login failure],2021-07-31 23:47:41.157000,2021-07-31 23:47:52.157000,11,test,15828
16201,16201,2021-07-31,mobservice,mobservice1,"2021-07-31 23:54:35,145 | WARNING | 0.0.0.1 | ...",WARNING,[login failure],2021-07-31 23:54:35.145000,2021-07-31 23:54:46.145000,11,test,16190
16202,16202,2021-07-31,mobservice,mobservice1,"2021-07-31 23:54:49,585 | WARNING | 0.0.0.1 | ...",WARNING,[login failure],2021-07-31 23:54:49.585000,2021-07-31 23:55:00.585000,11,test,16191
16203,16203,2021-07-31,mobservice,mobservice2,"2021-07-31 23:59:14,048 | WARNING | 0.0.0.4 | ...",WARNING,[login failure],2021-07-31 23:59:14.048000,2021-07-31 23:59:25.048000,11,test,15829
16204,16204,2021-07-31,mobservice,mobservice1,"2021-07-31 23:59:41,313 | WARNING | 0.0.0.1 | ...",WARNING,[login failure],2021-07-31 23:59:41.313000,2021-07-31 23:59:52.313000,11,test,16192

In [10]:
full_labels_new_index_df.to_csv('label_15_85_corrected_index.csv', index=False)

In [17]:
labels_without_login_failure_df = full_labels_df[
    full_labels_df['anomaly_type'] != '[login failure]'
]
labels_without_login_failure_df.shape

(727, 11)

In [7]:
full_labels_df.shape

(16205, 11)

In [18]:
print(labels_without_login_failure_df[labels_without_login_failure_df['data_type'] == 'train'].shape)
print(labels_without_login_failure_df[labels_without_login_failure_df['data_type'] == 'test'].shape)

(96, 11)
(631, 11)

In [19]:
labels_without_login_failure_df.to_csv('labels_without_login.csv', index=False)

In [16]:
full_labels_df['anomaly_type'].unique()

array(['[memory_anomalies]', '[normal memory freed label]',
       '[login failure]', '[file moving program]',
       '[access permission denied exception]'], dtype=object)

In [20]:

# tvdiag_labels_df['anomaly_type'].value_counts()
value_counts_with_percentages(labels_without_login_failure_df['anomaly_type'])

                                      count  percent
anomaly_type
[memory_anomalies]                      652    89.68
[file moving program]                    43     5.91
[normal memory freed label]              17     2.34
[access permission denied exception]     15     2.06

In [21]:
print('Train labels distribution without login failure')
value_counts_with_percentages(labels_without_login_failure_df[labels_without_login_failure_df['data_type'] == 'train']['anomaly_type'])

                             count  percent
anomaly_type
[memory_anomalies]              88    91.67
[file moving program]            6     6.25
[normal memory freed label]      2     2.08

In [23]:
print('Test labels distribution without login failure')
value_counts_with_percentages(labels_without_login_failure_df[labels_without_login_failure_df['data_type'] == 'test']['anomaly_type'])

Test labels distribution without login failure

                                      count  percent
anomaly_type
[memory_anomalies]                      564    89.38
[file moving program]                    37     5.86
[normal memory freed label]              15     2.38
[access permission denied exception]     15     2.38

In [24]:
print('Train labels distribution for full dataset')
value_counts_with_percentages(full_labels_df[full_labels_df['data_type'] == 'train']['anomaly_type'])

Train labels distribution for full dataset

                             count  percent
anomaly_type
[login failure]               2335    96.05
[memory_anomalies]              88     3.62
[file moving program]            6     0.25
[normal memory freed label]      2     0.08

In [25]:
print('Test labels distribution for full dataset')
value_counts_with_percentages(full_labels_df[full_labels_df['data_type'] == 'test']['anomaly_type'])

Test labels distribution for full dataset

                                      count  percent
anomaly_type
[login failure]                       13143    95.42
[memory_anomalies]                      564     4.09
[file moving program]                    37     0.27
[normal memory freed label]              15     0.11
[access permission denied exception]     15     0.11

In [3]:
full_dataset_corrected_df = pd.read_csv('label_15_85_corrected_index.csv')
full_dataset_corrected_df.head()

,index,datetime,service,instance,message,level,anomaly_type,st_time,ed_time,duration,data_type,old_index
0,0,2021-07-01,webservice,webservice2,"2021-07-01 11:16:52,953 | WARNING | 0.0.0.3 | ...",WARNING,[memory_anomalies],2021-07-01 11:06:52.953000,2021-07-01 11:16:52.953000,600,train,5
1,1,2021-07-01,dbservice,dbservice1,"2021-07-01 11:54:27,616 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-01 11:44:27.616000,2021-07-01 11:54:27.616000,600,train,0
2,2,2021-07-01,dbservice,dbservice1,"2021-07-01 12:25:08,804 | WARNING | 0.0.0.4 | ...",WARNING,[normal memory freed label],2021-07-01 12:25:08.804000,2021-07-01 12:35:08.804000,600,train,1
3,3,2021-07-01,dbservice,dbservice2,"2021-07-01 12:54:56,480 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-01 12:44:56.480000,2021-07-01 12:54:56.480000,600,train,3
4,4,2021-07-01,redisservice,redisservice1,"2021-07-01 13:18:43,143 | WARNING | 0.0.0.1 | ...",WARNING,[memory_anomalies],2021-07-01 13:08:43.143000,2021-07-01 13:18:43.143000,600,train,7

In [4]:
value_counts_with_percentages(full_dataset_corrected_df[full_dataset_corrected_df['data_type'] == 'test']['instance'])

               count  percent
instance
mobservice2     6637    48.18
mobservice1     6626    48.11
dbservice2        87     0.63
webservice1       78     0.57
webservice2       76     0.55
dbservice1        69     0.50
logservice1       55     0.40
logservice2       51     0.37
redisservice2     48     0.35
redisservice1     47     0.34

In [5]:
value_counts_with_percentages(full_dataset_corrected_df[full_dataset_corrected_df['data_type'] == 'train']['instance'])

               count  percent
instance
mobservice1     1190    48.95
mobservice2     1159    47.68
logservice2       13     0.53
webservice2       12     0.49
logservice1       12     0.49
redisservice2     10     0.41
dbservice1         9     0.37
redisservice1      9     0.37
dbservice2         9     0.37
webservice1        8     0.33

In [6]:
dataset_without_mobservice_df = full_dataset_corrected_df[full_dataset_corrected_df['service']!='mobservice']
dataset_without_mobservice_df

,index,datetime,service,instance,message,level,anomaly_type,st_time,ed_time,duration,data_type,old_index
0,0,2021-07-01,webservice,webservice2,"2021-07-01 11:16:52,953 | WARNING | 0.0.0.3 | ...",WARNING,[memory_anomalies],2021-07-01 11:06:52.953000,2021-07-01 11:16:52.953000,600,train,5
1,1,2021-07-01,dbservice,dbservice1,"2021-07-01 11:54:27,616 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-01 11:44:27.616000,2021-07-01 11:54:27.616000,600,train,0
2,2,2021-07-01,dbservice,dbservice1,"2021-07-01 12:25:08,804 | WARNING | 0.0.0.4 | ...",WARNING,[normal memory freed label],2021-07-01 12:25:08.804000,2021-07-01 12:35:08.804000,600,train,1
3,3,2021-07-01,dbservice,dbservice2,"2021-07-01 12:54:56,480 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-01 12:44:56.480000,2021-07-01 12:54:56.480000,600,train,3
4,4,2021-07-01,redisservice,redisservice1,"2021-07-01 13:18:43,143 | WARNING | 0.0.0.1 | ...",WARNING,[memory_anomalies],2021-07-01 13:08:43.143000,2021-07-01 13:18:43.143000,600,train,7
...,...,...,...,...,...,...,...,...,...,...,...,...
15976,15976,2021-07-31,webservice,webservice2,"2021-07-31 17:23:01,917 | WARNING | 0.0.0.3 | ...",WARNING,[memory_anomalies],2021-07-31 17:13:01.917000,2021-07-31 17:23:01.917000,600,test,15465
16060,16060,2021-07-31,redisservice,redisservice1,"2021-07-31 19:47:47,391 | WARNING | 0.0.0.1 | ...",WARNING,[memory_anomalies],2021-07-31 19:37:47.391000,2021-07-31 19:47:47.391000,600,test,16195
16073,16073,2021-07-31,logservice,logservice1,"2021-07-31 20:07:23,440 | WARNING | 0.0.0.3 | ...",WARNING,[memory_anomalies],2021-07-31 19:57:23.440000,2021-07-31 20:07:23.440000,600,test,16202
16135,16135,2021-07-31,logservice,logservice2,"2021-07-31 22:12:34,137 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-31 22:02:34.137000,2021-07-31 22:12:34.137000,600,test,16204
16176,16176,2021-07-31,dbservice,dbservice1,"2021-07-31 23:18:43,303 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-31 23:08:43.303000,2021-07-31 23:18:43.303000,600,test,15459

In [13]:
print('Train distribution')
value_counts_with_percentages(dataset_without_mobservice_df[dataset_without_mobservice_df['data_type'] == 'train']['instance'])

Train distribution

               count  percent
instance
logservice2       13    15.85
webservice2       12    14.63
logservice1       12    14.63
redisservice2     10    12.20
redisservice1      9    10.98
dbservice2         9    10.98
dbservice1         9    10.98
webservice1        8     9.76

In [14]:
print('Test distribution')
value_counts_with_percentages(dataset_without_mobservice_df[dataset_without_mobservice_df['data_type'] == 'test']['instance'])

Test distribution

               count  percent
instance
dbservice2        87    17.03
webservice1       78    15.26
webservice2       76    14.87
dbservice1        69    13.50
logservice1       55    10.76
logservice2       51     9.98
redisservice2     48     9.39
redisservice1     47     9.20

In [9]:
dataset_without_mobservice_df.to_csv('label_without_mobservice_correct_index.csv', index=False)

In [16]:
print('Train distribution for incident type')
value_counts_with_percentages(dataset_without_mobservice_df[dataset_without_mobservice_df['data_type'] == 'train']['anomaly_type'])

Train distribution for incident type

                             count  percent
anomaly_type
[memory_anomalies]              74    90.24
[file moving program]            6     7.32
[normal memory freed label]      2     2.44

In [15]:
print('Test distribution for incident type')
value_counts_with_percentages(dataset_without_mobservice_df[dataset_without_mobservice_df['data_type'] == 'test']['anomaly_type'])

Test distribution for incident type

                                      count  percent
anomaly_type
[memory_anomalies]                      446    87.28
[file moving program]                    37     7.24
[access permission denied exception]     15     2.94
[normal memory freed label]              13     2.54

In [5]:
# after reprocessing data with correct index
new_dataset_without_mobservice_df = full_labels_df[full_labels_df['service']!='mobservice']
new_dataset_without_mobservice_df.head()

,index,datetime,service,instance,message,level,anomaly_type,st_time,ed_time,duration,data_type
0,5,2021-07-01,webservice,webservice2,"2021-07-01 11:16:52,953 | WARNING | 0.0.0.3 | ...",WARNING,[memory_anomalies],2021-07-01 11:06:52.953000,2021-07-01 11:16:52.953000,600,train
1,0,2021-07-01,dbservice,dbservice1,"2021-07-01 11:54:27,616 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-01 11:44:27.616000,2021-07-01 11:54:27.616000,600,train
2,1,2021-07-01,dbservice,dbservice1,"2021-07-01 12:25:08,804 | WARNING | 0.0.0.4 | ...",WARNING,[normal memory freed label],2021-07-01 12:25:08.804000,2021-07-01 12:35:08.804000,600,train
3,3,2021-07-01,dbservice,dbservice2,"2021-07-01 12:54:56,480 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-01 12:44:56.480000,2021-07-01 12:54:56.480000,600,train
4,7,2021-07-01,redisservice,redisservice1,"2021-07-01 13:18:43,143 | WARNING | 0.0.0.1 | ...",WARNING,[memory_anomalies],2021-07-01 13:08:43.143000,2021-07-01 13:18:43.143000,600,train

In [6]:
print('Train distribution for incident type')
value_counts_with_percentages(new_dataset_without_mobservice_df[new_dataset_without_mobservice_df['data_type'] == 'train']['anomaly_type'])

Train distribution for incident type

                             count  percent
anomaly_type
[memory_anomalies]              74    90.24
[file moving program]            6     7.32
[normal memory freed label]      2     2.44

In [7]:
print('Test distribution for incident type')
value_counts_with_percentages(new_dataset_without_mobservice_df[new_dataset_without_mobservice_df['data_type'] == 'test']['anomaly_type'])

Test distribution for incident type

                                      count  percent
anomaly_type
[memory_anomalies]                      446    87.28
[file moving program]                    37     7.24
[access permission denied exception]     15     2.94
[normal memory freed label]              13     2.54

In [8]:
new_dataset_without_mobservice_df.to_csv('label_without_mobservice.csv', index=False)

In [10]:
# after reprocessing data with correct index
gaia_full_df = pd.read_csv('gaia.csv')
gaia_without_mobservice_df = gaia_full_df[gaia_full_df['service']!='mobservice']
gaia_without_mobservice_df.head()

,index,datetime,service,instance,message,level,anomaly_type,st_time,ed_time,duration,data_type
0,0,2021-07-01,dbservice,dbservice1,"2021-07-01 11:54:27,616 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-01 11:44:27.616000,2021-07-01 11:54:27.616000,600,train
1,1,2021-07-01,dbservice,dbservice1,"2021-07-01 12:25:08,804 | WARNING | 0.0.0.4 | ...",WARNING,[normal memory freed label],2021-07-01 12:25:08.804000,2021-07-01 12:35:08.804000,600,train
2,2,2021-07-01,dbservice,dbservice1,"2021-07-01 22:33:05,033 | WARNING | 0.0.0.4 | ...",WARNING,[memory_anomalies],2021-07-01 22:23:05.033000,2021-07-01 22:33:05.033000,600,train
3,3,2021-07-01,dbservice,dbservice2,"2021-07-01 12:54:56,480 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-01 12:44:56.480000,2021-07-01 12:54:56.480000,600,train
4,4,2021-07-01,dbservice,dbservice2,"2021-07-01 15:10:23,517 | WARNING | 0.0.0.2 | ...",WARNING,[memory_anomalies],2021-07-01 15:00:23.517000,2021-07-01 15:10:23.517000,600,train

In [11]:
gaia_without_mobservice_df.to_csv('gaia_without_mobservice.csv', index=False)

In [13]:
print('GAIA train distribution for incident type')
value_counts_with_percentages(gaia_without_mobservice_df[gaia_without_mobservice_df['data_type'] == 'train']['anomaly_type'])

GAIA train distribution for incident type

                             count  percent
anomaly_type
[memory_anomalies]              74    90.24
[file moving program]            6     7.32
[normal memory freed label]      2     2.44

In [14]:
print('Test distribution for incident type')
value_counts_with_percentages(gaia_without_mobservice_df[gaia_without_mobservice_df['data_type'] == 'test']['anomaly_type'])

Test distribution for incident type

                                      count  percent
anomaly_type
[memory_anomalies]                      446    87.28
[file moving program]                    37     7.24
[access permission denied exception]     15     2.94
[normal memory freed label]              13     2.54

In [15]:
print('GAIA train distribution for incident type')
value_counts_with_percentages(gaia_without_mobservice_df[gaia_without_mobservice_df['data_type'] == 'train']['instance'])

GAIA train distribution for incident type

               count  percent
instance
logservice2       13    15.85
webservice2       12    14.63
logservice1       12    14.63
redisservice2     10    12.20
redisservice1      9    10.98
dbservice2         9    10.98
dbservice1         9    10.98
webservice1        8     9.76

In [16]:
print('GAIA test distribution for incident type')
value_counts_with_percentages(gaia_without_mobservice_df[gaia_without_mobservice_df['data_type'] == 'test']['instance'])

GAIA test distribution for incident type

               count  percent
instance
dbservice2        87    17.03
webservice1       78    15.26
webservice2       76    14.87
dbservice1        69    13.50
logservice1       55    10.76
logservice2       51     9.98
redisservice2     48     9.39
redisservice1     47     9.20

In [17]:
print('GAIA full train distribution for incident type')
value_counts_with_percentages(gaia_full_df[gaia_full_df['data_type'] == 'train']['instance'])

GAIA full train distribution for incident type

               count  percent
instance
mobservice1     1190    48.95
mobservice2     1159    47.68
logservice2       13     0.53
webservice2       12     0.49
logservice1       12     0.49
redisservice2     10     0.41
dbservice2         9     0.37
dbservice1         9     0.37
redisservice1      9     0.37
webservice1        8     0.33

In [18]:
print('GAIA full test distribution for incident type')
value_counts_with_percentages(gaia_full_df[gaia_full_df['data_type'] == 'test']['instance'])

GAIA full test distribution for incident type

               count  percent
instance
mobservice2     6637    48.18
mobservice1     6626    48.11
dbservice2        87     0.63
webservice1       78     0.57
webservice2       76     0.55
dbservice1        69     0.50
logservice1       55     0.40
logservice2       51     0.37
redisservice2     48     0.35
redisservice1     47     0.34

In [4]:
gaia_full_df = pd.read_csv('gaia.csv')
value_counts_with_percentages(gaia_full_df[gaia_full_df['data_type'] == 'train']['anomaly_type'])

                             count  percent
anomaly_type
[login failure]               2335    96.05
[memory_anomalies]              88     3.62
[file moving program]            6     0.25
[normal memory freed label]      2     0.08

In [5]:
value_counts_with_percentages(gaia_full_df[gaia_full_df['data_type'] == 'test']['anomaly_type'])

                                      count  percent
anomaly_type
[login failure]                       13143    95.42
[memory_anomalies]                      564     4.09
[file moving program]                    37     0.27
[normal memory freed label]              15     0.11
[access permission denied exception]     15     0.11